<?php
// Quiosque público: a identidade é definida exclusivamente pela face cadastrada.
require_once __DIR__ . '/../../includes/config.php';
$requestPath = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH) ?: '';
if (substr($requestPath, -strlen('/modules/ponto/ponto_publico.php')) === '/modules/ponto/ponto_publico.php') {
    $canonicalBase = defined('SITE_URL') && SITE_URL !== ''
        ? rtrim(SITE_URL, '/')
        : ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . rtrim(BASE_URL, '/'));
    header('Location: ' . $canonicalBase . '/ponto-publico?' . http_build_query($_GET));
    exit;
}
$empresaId = (int) ($_GET['empresa'] ?? 0);
$chave = (string) ($_GET['chave'] ?? '');
$esperada = $empresaId > 0 ? hash_hmac('sha256', (string) $empresaId, DB_PASS . '|ponto-publico') : '';
if ($empresaId <= 0 || $chave === '' || !hash_equals($esperada, $chave)) {
    http_response_code(403);
    exit('Link público inválido. Gere um novo link no painel da empresa.');
}
?>
<!doctype html><html lang="pt-BR" data-bs-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bater ponto · Ponto Fácil</title><link rel="icon" href="<?= htmlspecialchars(BASE_URL) ?>/assets/favicon.svg"><link rel="stylesheet" href="<?= htmlspecialchars(rtrim(BASE_URL, '/')) ?>/assets/css/style.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><style>
body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:var(--pf-gradient);font-family:var(--bs-font-sans-serif);color:var(--text-primary)}.card{width:min(100%,500px);overflow:hidden;background:var(--bg-primary);border:1px solid var(--border-color);border-radius:22px;box-shadow:0 24px 70px #0f172a40;text-align:center}.card-head{padding:28px 24px 24px;background:var(--pf-gradient);color:#fff}.card-head .brand{font-size:38px}.card-head h1{margin:8px 0 4px;color:#fff;font-size:24px}.card-head p{margin:0;color:#e0e7ff}.card-body{padding:24px}.hint{color:var(--text-secondary);line-height:1.5;margin:0 0 20px}.camera{position:relative;aspect-ratio:4/3;overflow:hidden;border-radius:16px;background:#111827;margin:0 0 16px}.camera video{width:100%;height:100%;object-fit:cover;transform:scaleX(-1)}.guide{position:absolute;inset:15% 25%;border:3px solid #ffffffbb;border-radius:48%;box-shadow:0 0 0 999px #0003}.status{min-height:48px;padding:13px;border-radius:12px;background:color-mix(in srgb,var(--pf-primary) 10%,var(--bg-secondary));color:var(--pf-primary);font-weight:700}.status.error{background:#fef2f2;color:#b91c1c}.status.success{background:#ecfdf5;color:#047857}.button{width:100%;padding:15px;border:0;border-radius:12px;background:var(--pf-gradient);color:#fff;font-size:16px;font-weight:800;cursor:pointer;margin-top:16px}.button.secondary{background:var(--bg-secondary);color:var(--pf-primary);border:1px solid var(--border-color)}.button:disabled{opacity:.55;cursor:wait}.privacy{font-size:12px;color:var(--text-muted);margin:18px 0 0}
</style><script>document.documentElement.setAttribute('data-bs-theme',localStorage.getItem('pf_theme')||'light')</script></head><body><main class="card"><header class="card-head"><div class="brand"><i class="fa-solid fa-face-smile"></i></div><h1>Bater ponto</h1><p>Registro rápido e seguro</p></header><section class="card-body"><p class="hint">Posicione apenas uma pessoa diante da câmera ou use a biometria cadastrada no dispositivo.</p><div class="camera"><video id="video" autoplay muted playsinline></video><div class="guide"></div></div><div id="status" class="status">Carregando reconhecimento facial…</div><button id="punch" class="button" disabled><i class="fa-solid fa-camera"></i> Aguardando câmera</button><button id="devicePunch" class="button secondary"><i class="fa-solid fa-fingerprint"></i> Bater ponto com biometria</button><p class="privacy"><i class="fa-solid fa-shield-halved"></i> A biometria permanece protegida no dispositivo. A localização é registrada junto à batida.</p></section></main>
<script src="<?= htmlspecialchars(rtrim(BASE_URL, '/')) ?>/assets/js/face-api.min.js"></script><script src="<?= htmlspecialchars(rtrim(BASE_URL, '/')) ?>/assets/js/passkey.js"></script><script>
window.pfGetLocation=()=>new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Seu navegador não oferece localização.'));navigator.geolocation.getCurrentPosition(position=>resolve(position.coords),()=>reject(new Error('Permita a localização precisa para registrar o ponto.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0})});
const pfNativeFetch=window.fetch.bind(window);const pfShowSuccess=(result)=>{const data=result.data||{};const modal=document.createElement('div');modal.style.cssText='position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.72);backdrop-filter:blur(6px)';modal.innerHTML='<div style="width:min(100%,420px);padding:32px 26px;text-align:center;border-radius:22px;background:var(--bg-primary,#fff);color:var(--text-primary,#0f172a);box-shadow:0 24px 70px rgba(0,0,0,.3)"><div style="width:72px;height:72px;margin:0 auto 18px;display:grid;place-items:center;border-radius:50%;background:#dcfce7;color:#16a34a;font-size:34px"><i class="fa-solid fa-check"></i></div><h2 style="margin:0 0 8px">Batida registrada!</h2><p style="margin:0;color:var(--text-secondary,#64748b)">'+(data.tipo_nome||'Ponto')+' registrada para <strong>'+(data.funcionario||'colaborador')+'</strong>.</p><p style="margin:18px 0 0;font-size:13px;color:var(--text-muted,#64748b)">Próximo colaborador em <strong id="pfReloadCount">3</strong> segundos.</p></div>';document.body.appendChild(modal);let seconds=3;const counter=modal.querySelector('#pfReloadCount');const timer=setInterval(()=>{seconds-=1;if(counter)counter.textContent=seconds;if(seconds<=0){clearInterval(timer);location.reload()}},1000)};window.fetch=async(input,init={})=>{if(String(input).includes('/api/biometrico.php')&&init.body){try{const payload=JSON.parse(init.body);if(payload.acao==='registrar_ponto_facial_publico'){const coords=await window.pfGetLocation();payload.latitude=coords.latitude;payload.longitude=coords.longitude;payload.precisao=coords.accuracy;init={...init,body:JSON.stringify(payload)}}}catch(error){throw error}}const response=await pfNativeFetch(input,init);if(String(input).includes('/api/biometrico.php')&&init.body){try{const copy=response.clone();const result=await copy.json();if(result.success&&result.data?.funcionario_id)pfShowSuccess(result)}catch(_){}}return response};
(()=>{const base=<?= json_encode(rtrim(BASE_URL,'/')) ?>,empresa=<?= (int)$empresaId ?>,chave=<?= json_encode($chave) ?>,video=document.querySelector('#video'),status=document.querySelector('#status'),button=document.querySelector('#punch');let stream,face,working=false,ready=false;const say=(message,type='')=>{status.textContent=message;status.className='status '+type};async function boot(){try{if(!window.isSecureContext&&!['localhost','127.0.0.1','::1'].includes(location.hostname))throw Error('A câmera exige HTTPS.');await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(base+'/assets/models'),faceapi.nets.faceLandmark68Net.loadFromUri(base+'/assets/models'),faceapi.nets.faceRecognitionNet.loadFromUri(base+'/assets/models')]);stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:540}},audio:false});video.srcObject=stream;await video.play();ready=true;button.disabled=false;button.innerHTML='<i class="fa-solid fa-camera"></i> Bater ponto';say('Centralize seu rosto no guia.');setInterval(scan,700)}catch(error){say(error.message||'Não foi possível iniciar a câmera.','error')}}async function scan(){if(!ready||working||window.pfPasskeyWorking||!video.videoWidth)return;try{const detections=await faceapi.detectAllFaces(video,new faceapi.TinyFaceDetectorOptions({inputSize:224,scoreThreshold:.58})).withFaceLandmarks().withFaceDescriptors();face=detections.length===1?detections[0]:null;say(detections.length===1?'Rosto detectado. Toque para registrar.':detections.length>1?'Deixe apenas uma pessoa no enquadramento.':'Posicione o rosto no guia.')}catch(_){}}async function punch(){if(working||!face){say('Aguarde um rosto único ser detectado.','error');return}working=true;button.disabled=true;say('Validando sua face e registrando ponto…');try{const response=await fetch(base+'/api/biometrico.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({acao:'registrar_ponto_facial_publico',empresa_id:empresa,chave,descritor:Array.from(face.descriptor)})});const result=await response.json();if(!response.ok||!result.success)throw Error(result.message||result.error||'Rosto não reconhecido.');say((result.data?.tipo_nome||'Ponto')+' registrado para '+(result.data?.funcionario||'funcionário')+'.','success');button.innerHTML='<i class="fa-solid fa-check"></i> Registrado com sucesso';if(stream)stream.getTracks().forEach(track=>track.stop())}catch(error){say(error.message||'Rosto não reconhecido. Tente novamente.','error');working=false;button.disabled=false}}button.addEventListener('click',punch);window.addEventListener('beforeunload',()=>stream&&stream.getTracks().forEach(track=>track.stop()));boot()})();
document.querySelector('#devicePunch').addEventListener('click',async function(){const button=this,status=document.querySelector('#status');window.pfPasskeyWorking=true;button.disabled=true;status.className='status';status.textContent='Aguardando biometria e localização…';try{if(!window.PublicKeyCredential||!navigator.credentials)throw Error('Este dispositivo não oferece suporte à biometria para sites.');const coords=await window.pfGetLocation();let response=await fetch(<?= json_encode(rtrim(BASE_URL,'/').'/api/passkey.php') ?>,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({acao:'ponto_opcoes',empresa_id:<?= (int)$empresaId ?>,chave:<?= json_encode($chave) ?>})}),result=await response.json();if(!response.ok||!result.success)throw Error(result.message);const credential=await navigator.credentials.get(PFPasskey.prepareGet(result.data.options));response=await fetch(<?= json_encode(rtrim(BASE_URL,'/').'/api/passkey.php') ?>,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({acao:'ponto_concluir',latitude:coords.latitude,longitude:coords.longitude,id:PFPasskey.encode(credential.rawId),clientDataJSON:PFPasskey.encode(credential.response.clientDataJSON),authenticatorData:PFPasskey.encode(credential.response.authenticatorData),signature:PFPasskey.encode(credential.response.signature),userHandle:PFPasskey.encode(credential.response.userHandle)})});result=await response.json();if(!response.ok||!result.success)throw Error(result.message);status.className='status success';status.textContent=result.message;pfShowSuccess({data:result.data})}catch(error){status.className='status error';status.textContent=error.message||'Não foi possível registrar o ponto com biometria.';button.disabled=false;window.pfPasskeyWorking=false}});
</script></body></html>
